### ISSUE TITLE
Don't work if username and password is different

### ISSUE THREAD

**Issue by GreyXor** [lauslim12/basic#5]
Hello, thanks for this lib
This lib seems to only work when username and password it's the same, which is quite strange.
Look this line https://github.com/lauslim12/basic/blob/main/basic.go#L92
users[username] is returning the password, not the username. Then this comparison is wrong

**Comment by lauslim12** [comment]
Thank you so much for reporting this error. I just realized the comparison is wrong and would be fixing this as soon as possible.

**Comment by lauslim12** [comment]
I have updated the library with this pull request: https://github.com/lauslim12/basic/pull/6, and have released a new library version (https://github.com/lauslim12/basic/releases/tag/v1.0.5 -- https://pkg.go.dev/github.com/lauslim12/basic@v1.0.5) which addresses this issue. I have also added more tests to catch this bug.

Please take a look when you have time, and thank you again for reporting this problem!

**Comment by GreyXor** [comment]
I will test it now, thanks for your reactivity

**Comment by GreyXor** [comment]
Work as expected to me :heavy_check_mark:

**Comment by lauslim12** [comment]
Thank you so much! ❤️
